# =============================================================================
# Pipeline - Configuração de Modelos de Aprendizado
# =============================================================================
#
# Bloco global_config (nível raiz):
#   dataset:
#     arquivo     : nome do arquivo em data/processed a ser usado para ML sup/não supervisionado (padrão: main_dataframe.csv)
#     features    : lista de colunas a serem usadas como features para ML sup/não supervisionado (padrão: todas as colunas utilizadas no cálculo do IDS, exceto é claro o IDS)
#     target_col  : coluna a ser usada como alvo para os modelos supervisionados (padrão: 'ids')
#   preprocessing:
#     scale       : se true, aplica padronização (StandardScaler) a todas as features (padrão: true)
#     scaler      : tipo de scaler a ser usado (padrão: StandardScaler)
#
# Bloco ml_supervised (nível raiz):
#   enabled                 : habilita a execução do módulo de ML supervisionado (padrão: true)
#   fine-tuning_exploration : habilita a execução da exploração de hiperparâmetros dos módulos utilizando kfold/cv (padrão: false (por ser pesado))
#   split:
#     global_test_size    : proporção do dataset a ser usado como teste (padrão: 0.2)
#     global_random_state : semente para divisão aleatória (padrão: 42)
#   models:
#     - nome            : nome do modelo (ex: 'Random Forest Regressor (Depth=10)')
#       tipo            : tipo do modelo (Tipos disponíveis: LinearRegression, KNNRegressor, SVR, DecisionTreeRegressor, RandomForestRegressor, GradientBoostingRegressor, ExtraTreesRegressor, HistGradientBoostingRegressor, Lasso, Ridge)
#       features        : lista de colunas extras a serem usadas como features para este modelo (padrão: global_features + features)
#       drop_cols       : lista de colunas a serem excluídas para este modelo (padrão: [])
#       hyperparameters : dicionário de hiperparâmetros específicos para este modelo (padrão: {})
#       notas           : notas livres sobre o modelo
#
# TODO: Escrever as descrições do campo novo assim como criar seu template
#
# =============================================================================
global_config:
  dataset:
    arquivo: main_dataframe.csv
    features: ['hospital_estadual', 'hospital_federal', 'hospital_municipal', 'hospital_particular', 'clinica_estadual', 'clinica_federal', 'clinica_municipal', 'clinica_particular', 'consultorio_total', 'pronto_atendimento_total', 'unidade_movel_total', 'baixissima vulnerabilidade_n_pessoas', 'muito baixa vulnerabilidade_n_pessoas', 'baixa vulnerabilidade_n_pessoas', 'media vulnerabilidade_n_pessoas', 'alta vulnerabilidade_n_pessoas', 'muito alta vulnerabilidade_n_pessoas', 'vigilancia em saude', 'consultas / atendimentos / acompanhamentos', 'diagnostico em vigilancia epidemiologica e ambiental', 'diagnostico em laboratorio clinico', 'coleta de material', 'tratamentos clinicos (outras especialidades)', 'diagnostico por ultrasonografia', 'diagnostico por radiologia', 'fisioterapia', 'tratamentos odontologicos', 'diagnostico por teste rapido', 'terapias especializadas', 'diagnostico por tomografia', 'diagnostico por ressonancia magnetica', 'pequenas cirurgias e cirurgias de pele, tecido subcutaneo e mucosa', 'diagnostico por endoscopia', 'metodos diagnosticos em especialidades', 'diagnostico por anatomia patologica e citopatologia', 'bucomaxilofacial', 'diagnostico por radiologia intervencionista', 'anestesiologia', 'hemoterapia', 'diagnostico e procedimentos especiais em hemoterapia', 'diagnostico por medicina nuclear in vivo', 'tratamento em oncologia', 'tratamento em nefrologia', 'componente especializado da assitencia farmaceutica', 'orteses, proteses e materiais especiais nao relacionados ao ato cirurgico', 'autorizacao / regulacao', 'acoes coletivas / individuais em saude', 'acoes relacionadas ao estabelecimento', 'tratamento de lesoes, envenenamentos e outros, decorrentes de causas externas', 'cirurgia do aparelho circulatorio', 'cirurgia do sistema nervoso central e periferico', 'parto e nascimento', 'medicamentos de ambito hospitalar e urgencia', 'cirurgia do aparelho digestivo, orgaos anexos e parede abdominal', 'cirurgia do sistema osteomuscular', 'cirurgia obstetrica', 'cirurgia toracica', 'cirurgia em oncologia', 'acoes relacionadas ao atendimento', 'cirurgia do aparelho geniturinario', 'cirurgia reparadora', 'cirurgia das vias aereas superiores, da face, da cabeca e do pescoco', 'cirurgia de mama', 'orteses, proteses e materiais especiais relacionados ao ato cirurgico', 'acompanhamento e intercorrencias no pre e pos-transplante', 'cirurgia do aparelho da visao', 'cirurgia de glandulas endocrinas', 'cirurgia em nefrologia', 'outras cirurgias', 'coleta e exames para fins de doacao de orgaos, tecidos e celulas e de transplante', 'acoes relacionadas a doacao de orgaos e tecidos para transplante', 'processamento de tecidos para transplante', 'transplante de orgaos, tecidos e celulas', 'avaliacao de morte encefalica', 'populacao', 'receita_anual']
    target_col: 'ids'

  preprocessing:
    scale: true
    scaler: StandardScaler

    # Usado apenas para exploração de fine-tuning, supervisionado/não supervisionado possuem suas próprias configurações
    pca:
      fine-tuning_exploration: false
      tipo: PCA

ml_supervised:
  enabled: true
  fine-tuning_exploration: false

  split:
    global_test_size: 0.15
    global_random_state: 42
  
  pca:
    enabled: false

    tipo: KernelPCA
    hyperparameters:
      n_components: 50
      kernel: rbf
      random_state: 42
      gamma: 0.01

  models:
    - nome: 'Gradient Boosting Regressor'
      tipo: GradientBoostingRegressor
      features: []
      drop_cols: []
      hyperparameters:
        n_estimators: 300
        learning_rate: 0.1
        subsample: 0.6
        min_samples_split: 20
        min_samples_leaf: 3
        max_features: 0.5
        max_depth: 3
        loss: 'huber'
      notas: 'Modelo de regressão GradientBoosting feito a partir de um fine-tuning bastante seleto com cada campo, em comparação com milhares de outros hiperparâmetros. Resultado final após diversos testes e fits com ele se demonstrarem satisfatórios.'
    - nome: 'Hist Gradient Boosting Regressor'
      tipo: HistGradientBoostingRegressor
      features: []
      drop_cols: []
      hyperparameters:
        max_iter: 500
        learning_rate: 0.15
        validation_fraction: 0.1
        n_iter_no_change: 20
        min_samples_leaf: 10
        max_leaf_nodes: 7
        max_bins: 255
        l2_regularization: 0.001
        early_stopping: True
      notas: 'Modelo de regressão HistGradientBoosting mais robusto de modo geral tanto para os testes como predição de dados desconhecidos, alcançado resultados satisfatórios mas ainda não ideais.'

ml_unsupervised:
  enabled: true
  fine-tuning_exploration: false

  pca:
    enabled: true

    tipo: KernelPCA
    hyperparameters:
      n_components: 20
      kernel: rbf
      random_state: 42
      gamma: 0.01

  models:
    - nome: 'KMeans Clustering'
      tipo: KMeans
      features: []
      drop_cols: []
      hyperparameters:
        n_clusters: 6
        init: 'k-means++'
        n_init: 10
        max_iter: 300
        random_state: 42
      notas: 'Modelo de clustering KMeans para análise exploratória, ainda em fase de testes e ajustes.'

  # ── Template para novos modelos supervisionados ───────────────────────────────────────────
  # - nome: 'Nome do Modelo, ex: Regressor Furacão 2000'
  #   tipo: Tipo do modelo, ex: RandomForestRegressor (consultar lista acima de tipos)
  #   features: [col_x, col_y], colunas extras a serem usadas como features para esse modelo (opcional, padrão: global_features + features)
  #   drop_cols: [col_z], colunas a serem excluídas para esse modelo (opcional, padrão: [])
  #   hyperparameters:
  #     param_1: valor_1
  #     param_2: valor_2
  #     ..., lista de hiperparâmetros específicos do tipo de modelo selecionado, em dúvida consulte a documentação do modelo no scikit-learn
  #   notas: "Anotações que você quiser fazer sobre o modelo, como detalhes do fine-tuning, resultados de testes, expectativas ou qualquer coisa que você ache relevante ou sentir vontade de colocar."